
[functions.process-sync-jobs]
enabled = true
verify_jwt = true
import_map = "./functions/process-sync-jobs/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/process-sync-jobs/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/process-sync-jobs/*.html" ]

[functions.sync-microsoft-licenses]
enabled = true
verify_jwt = true
import_map = "./functions/sync-microsoft-licenses/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/sync-microsoft-licenses/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/sync-microsoft-licenses/*.html" ]
